Repository equinor/webviz-ert, pull requests merged in 2022-07, with the labels that each got.

#290 Separate plots in plot viewer
  webviz_ert/controllers/plot_view_controller.py
  webviz_ert/plugins/_response_comparison.py
  webviz_ert/views/parameter_view.py
  webviz_ert/views/plot_view.py
  webviz_ert/views/response_view.py
Labels: improvement, user request

#307 Finish test for axes labels
  tests/views/test_response_correlation.py
Labels: bug

#309 Add a beta label
  tests/conftest.py
  tests/views/test_observation_view.py
  tests/views/test_parameter_selector.py
  tests/views/test_plot_view.py
  tests/views/test_response_correlation.py
  webviz_ert/assets/ert-style.css
  webviz_ert/assets/webviz-config.yml
  webviz_ert/plugins/_observation_analyzer.py
  webviz_ert/plugins/_parameter_comparison.py
  webviz_ert/plugins/_response_comparison.py
  webviz_ert/plugins/_response_correlation.py
Labels: improvement

#316 Change layout from 4x1 to 2x2
  webviz_ert/plugins/_response_correlation.py
Labels: improvement, user request

#320 Add column names to heatmap
  webviz_ert/controllers/response_correlation_controller.py
Labels: improvement, user request

#330 Fix response overview plot to survive reloads
  webviz_ert/controllers/response_correlation_controller.py
Labels: bug
