Repository equinor/webviz-ert, pull requests merged in 2022-06, with the labels that each got.

#262 Fix failing test_webviz_observation_analyzer running on jenkins
  tests/conftest.py
  tests/data/snake_oil_data.py
  tests/data/spe1_st/tests/test_webviz_ert.py
  tests/test_data_loader.py
  tests/views/test_ensemble_selector.py
  tests/views/test_observation_view.py
  webviz_ert/controllers/observation_response_controller.py
  webviz_ert/views/misfit_view.py
Labels: bug

#263 Fix deselection of multiple ensembles
  tests/views/test_plot_view.py
  webviz_ert/controllers/ensemble_selector_controller.py
Labels: bug

#277 Add hint to use config file during start up
  README.md
Labels: documentation

#275 Suggestions from a first overview of the code
  CONTRIBUTING.md
  webviz_ert/controllers/link_and_brush_controller.py
  webviz_ert/views/parallel_coordinates_view.py
  webviz_ert/views/parameter_view.py
Labels: good first issue
